# Generated by Django 4.2.26 on 2025-11-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftEntryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='shift_videos/')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='buch.shiftentry')),
            ],
        ),
    ]
