# Generated by Django 4.2.26 on 2025-11-30 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftentry',
            name='spare_part_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Beschreibung des Ersatzteils'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='spare_part_quantity_remaining',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bestand nach Entnahme'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='spare_part_quantity_used',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Entnommene Anzahl'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='spare_part_sap_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='SAP-Nummer'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='used_spare_parts',
            field=models.BooleanField(default=False, verbose_name='Ersatzteile verwendet'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('entry', 'user')},
        ),
    ]
