# Generated by Django 4.2.26 on 2025-11-30 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0004_shiftentry_spare_part_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftEntryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('action_time', models.DateTimeField()),
                ('status_before', models.CharField(blank=True, choices=[('OFFEN', 'Offen'), ('IN_ARB', 'In Bearbeitung'), ('ERLED', 'Erledigt')], max_length=10)),
                ('status_after', models.CharField(blank=True, choices=[('OFFEN', 'Offen'), ('IN_ARB', 'In Bearbeitung'), ('ERLED', 'Erledigt')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='buch.shiftentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['action_time', 'id'],
            },
        ),
    ]
