# Generated by Django 4.2.26 on 2025-11-30 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0005_shiftentryupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_quantity_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_quantity_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_sap_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='used_spare_parts',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_number', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity_used', models.PositiveIntegerField(default=0)),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='buch.shiftentry')),
            ],
            options={
                'verbose_name': 'Ersatzteil',
                'verbose_name_plural': 'Ersatzteile',
            },
        ),
    ]
