# Generated by Django 4.2.26 on 2025-12-01 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0006_alter_shiftentry_spare_part_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftentryupdate',
            options={'ordering': ['action_time', 'id'], 'verbose_name': 'Ergänzung', 'verbose_name_plural': 'Ergänzungen'},
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='like',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='buch.shiftentry', verbose_name='Eintrag'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='category',
            field=models.CharField(choices=[('STOER', 'Störung'), ('WART', 'Wartung'), ('UMBAU', 'Umbau'), ('KONT', 'Kontrolle / Inspektion')], max_length=10, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buch.machine', verbose_name='Maschine'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='priority',
            field=models.PositiveIntegerField(default=2, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='shift',
            field=models.CharField(choices=[('F', 'Frühschicht'), ('S', 'Spätschicht'), ('N', 'Nachtschicht')], max_length=1, verbose_name='Schicht'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='(alt) Ersatzteil-Beschreibung'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_quantity_remaining',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='(alt) Bestand nach Entnahme'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_quantity_used',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='(alt) Entnommene Anzahl'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_sap_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='(alt) SAP-Nummer'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='status',
            field=models.CharField(choices=[('OFFEN', 'Offen'), ('IN_ARB', 'In Bearbeitung'), ('ERLED', 'Erledigt')], default='OFFEN', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='used_spare_parts',
            field=models.BooleanField(default=False, verbose_name='(alt) Ersatzteile verwendet'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='shiftentryimage',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='shiftentryimage',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buch.shiftentry', verbose_name='Eintrag'),
        ),
        migrations.AlterField(
            model_name='shiftentryimage',
            name='image',
            field=models.ImageField(upload_to='shift_images/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='shiftentryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='action_time',
            field=models.DateTimeField(verbose_name='Zeitpunkt der Maßnahme'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='comment',
            field=models.TextField(verbose_name='Ergänzung / Kommentar'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='buch.shiftentry', verbose_name='Eintrag'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='status_after',
            field=models.CharField(blank=True, choices=[('OFFEN', 'Offen'), ('IN_ARB', 'In Bearbeitung'), ('ERLED', 'Erledigt')], max_length=10, verbose_name='Status nachher'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='status_before',
            field=models.CharField(blank=True, choices=[('OFFEN', 'Offen'), ('IN_ARB', 'In Bearbeitung'), ('ERLED', 'Erledigt')], max_length=10, verbose_name='Status vorher'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='shiftentryvideo',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='shiftentryvideo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='buch.shiftentry', verbose_name='Eintrag'),
        ),
        migrations.AlterField(
            model_name='shiftentryvideo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am'),
        ),
        migrations.AlterField(
            model_name='shiftentryvideo',
            name='video',
            field=models.FileField(upload_to='shift_videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='buch.shiftentry', verbose_name='Eintrag'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='quantity_remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='Bestand nach Entnahme'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='quantity_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Entnommene Anzahl'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sap_number',
            field=models.CharField(max_length=50, verbose_name='SAP-Nummer'),
        ),
    ]
