# Generated by Django 4.2.26 on 2025-12-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0007_alter_shiftentryupdate_options_shiftentry_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='spare_parts_processed',
            field=models.BooleanField(default=False, help_text='Wird von Meister/Admin gesetzt, wenn die Ersatzteil-Entnahme in SAP erfasst/verbucht wurde.', verbose_name='Ersatzteile in SAP verbucht'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='spare_parts_processed_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der Bestätigung der SAP-Buchung.', null=True, verbose_name='SAP-Buchung bestätigt am'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='spare_parts_processed_by',
            field=models.ForeignKey(blank=True, help_text='Benutzer (typischerweise Meister/Admin), der die SAP-Buchung bestätigt hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_processed_entries', to=settings.AUTH_USER_MODEL, verbose_name='SAP-Buchung bestätigt von'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Gibt an, ob die Maschine aktuell aktiv/in Betrieb ist.'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, help_text="Standort der Maschine, z.B. 'Halle 2'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, help_text="Hersteller, z.B. 'Siemens'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(help_text="Kurzbezeichnung der Maschine, z.B. 'RBG-01'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='date',
            field=models.DateField(help_text='Datum des Ereignisses.', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='description',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung des Vorgangs.', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Geschätzte oder tatsächliche Dauer des Vorgangs.', null=True, verbose_name='Dauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='priority',
            field=models.PositiveIntegerField(default=2, help_text='1 = hoch, 2 = normal, 3 = niedrig.', verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_description',
            field=models.CharField(blank=True, help_text='Freitext-Beschreibung des Ersatzteils.', max_length=200, verbose_name='(alt) Ersatzteil-Beschreibung'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_quantity_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Restbestand nach der Entnahme.', null=True, verbose_name='(alt) Bestand nach Entnahme'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_quantity_used',
            field=models.PositiveIntegerField(blank=True, help_text='Wie viele Stück wurden entnommen?', null=True, verbose_name='(alt) Entnommene Anzahl'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='spare_part_sap_number',
            field=models.CharField(blank=True, help_text='SAP-Nummer des Ersatzteils.', max_length=50, verbose_name='(alt) SAP-Nummer'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='time',
            field=models.TimeField(blank=True, default=None, help_text='Uhrzeit des Ereignisses (optional).', null=True, verbose_name='Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='title',
            field=models.CharField(help_text='Kurzbeschreibung des Vorgangs.', max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='used_spare_parts',
            field=models.BooleanField(default=False, help_text='Wurde bei diesem Vorgang mindestens ein Ersatzteil verwendet?', verbose_name='(alt) Ersatzteile verwendet'),
        ),
        migrations.AlterField(
            model_name='shiftentry',
            name='user',
            field=models.ForeignKey(help_text='Mitarbeiter, der den Eintrag erstellt hat.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='shiftentryimage',
            name='comment',
            field=models.CharField(blank=True, help_text='Kurzer Kommentar zum Bild.', max_length=200, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='action_time',
            field=models.DateTimeField(help_text='Wann die Maßnahme durchgeführt wurde.', verbose_name='Zeitpunkt der Maßnahme'),
        ),
        migrations.AlterField(
            model_name='shiftentryupdate',
            name='comment',
            field=models.TextField(help_text='Beschreibung der durchgeführten Maßnahme oder Ergänzung.', verbose_name='Ergänzung / Kommentar'),
        ),
        migrations.AlterField(
            model_name='shiftentryvideo',
            name='comment',
            field=models.CharField(blank=True, help_text='Kurzer Kommentar zum Video.', max_length=200, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Benutzer, der diese Ersatzteil-Info erfasst hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.CharField(blank=True, help_text='Freitext-Beschreibung des Ersatzteils.', max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='quantity_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Restbestand nach Entnahme.', verbose_name='Bestand nach Entnahme'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='quantity_used',
            field=models.PositiveIntegerField(default=0, help_text='Wie viele Stück wurden entnommen?', verbose_name='Entnommene Anzahl'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sap_number',
            field=models.CharField(help_text='SAP-Nummer des Ersatzteils.', max_length=50, verbose_name='SAP-Nummer'),
        ),
    ]
