# Generated by Django 4.2.26 on 2025-12-10 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0008_alter_like_options_shiftentry_spare_parts_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftentry',
            name='additional_workers',
            field=models.ManyToManyField(blank=True, help_text='Weitere Kollegen, die an diesem Vorgang beteiligt waren.', related_name='shift_entries_as_worker', to=settings.AUTH_USER_MODEL, verbose_name='Weitere Mitarbeiter'),
        ),
    ]
