# Generated by Django 4.2.26 on 2025-12-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0009_shiftentry_additional_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ENTRY', 'Eintrag'), ('UPDATE', 'Ergänzung')], default='ENTRY', max_length=10, verbose_name='Quelle')),
                ('text_snippet', models.CharField(blank=True, max_length=255, verbose_name='Textauszug')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_notifications', to='buch.shiftentry', verbose_name='Eintrag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
